In [2]:
import numpy as np
import Example_matrices as ex
import dynamic_low_rank as dlr
import time_integration_low_rank as tilr
import Variable_step_size_integrator as vssi

## Spørsmål

- Hvordan skal man kunne teste dlr?
    - hva slags A skal det fungere på
    - testing av Fu, gir matrise med elementer på størrelse $10^{-16}$  
    - (ekstra) hvordan ser man at B = CD.T
<br>

- Variable solver er litt rar.
    - kan ikke konvergere da steglengden kun minkes.
    - Står ikke noe sted i psduokoden at U,S,V skal oppdateres.


In [2]:
# testing av Fu med dlr implementasjon

A_dot = ex.A_dot(0, epsilon = 1/2)
U, S, V = vssi.construct_U_S_V_0(A_dot)

A_dot = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

U, S, V = vssi.construct_U_S_V_0(A_dot)

def FU(U,A_dot,V,S):
    I_mm = np.eye(U.shape[0])
    return (I_mm-U@U.T)@A_dot@V@np.linalg.inv(S)

FUj = FU(U,A_dot,V,S)

print(FUj)


[[ 4.09624355e-16 -1.09367955e-16 -8.92694738e-16]
 [ 2.65132328e-16 -4.00778384e-17 -4.46347369e-16]
 [ 7.66498579e-16 -1.06375492e-16 -8.92694738e-16]]


In [5]:
t = 1.1
h = 1
tol = 50
A = ex.A(0, epsilon = 1/2)
A_dot = ex.A_dot(0, epsilon = 1/2)
U, S, V = vssi.construct_U_S_V_0(A_dot)

In [4]:
# test av dynamic_low_rank
vals = dlr.second_order_method(h,t,U,V,S)

In [8]:
# test av variable step size integrator for dynamic low rank

# never convergeces
U1,S1,V1,j = vssi.variable_solver(0,1,A_dot,tol,h,dlr.second_order_method)

count 0 j 0 t 0 h 1 u 10.0 v 10.0 s 56.114 

action 1 sigma 4453.519507642004 tol 50
count 1 j 0 t 0 h 0.5 u 10.0 v 10.0 s 56.114 

action 1 sigma 1951.472622349573 tol 50
count 2 j 0 t 0.0 h 0.25 u 10.0 v 10.0 s 56.114 

action 1 sigma 892.883269890158 tol 50
count 3 j 0 t 0.0 h 0.125 u 10.0 v 10.0 s 56.114 

action 1 sigma 423.7036723513778 tol 50
count 4 j 0 t 0.0 h 0.0625 u 10.0 v 10.0 s 56.114 

action 1 sigma 205.89526825999195 tol 50
count 0 j 1 t 0.0625 h 0.03125 u 10.0 v 10.0 s 201.955 

action 1 sigma 95.27830214479746 tol 50
count 1 j 1 t 0.0625 h 0.015625 u 10.0 v 10.0 s 201.955 

action 2 sigma 47.27692116185055 tol 50
count 0 j 2 t 0.078125 h 0.0109375 u 10.0 v 10.0 s 247.008 

action 2 sigma 32.505502265178706 tol 50
count 0 j 3 t 0.0890625 h 0.007656249999999999 u 10.0 v 10.0 s 278.416 

action 3 sigma 22.469783531761916 tol 3.125
count 0 j 4 t 0.09671875 h 0.007656249999999999 u 10.0 v 10.0 s 300.291 

action 3 sigma 22.298406142815445 tol 3.125
count 0 j 5 t 0.1043750

KeyboardInterrupt: 

In [5]:
print(np.linalg.norm(U1@S1@V1-A))

2489.117427475082


In [6]:
# test av time_integration_low_rank.py
vals = tilr.second_order_method(0.5,t,U,V,S)

In [7]:
# test av variable step size integrator for time_integration_low_rank.py

U1,S1,V1,j = vssi.variable_solver(0,1,A_dot,tol,0.5,tilr.second_order_method)

A_approx = U1@S1@V1.T

print(np.linalg.norm(A_approx-A))

count 0 j 0 t 0 h 0.5 u 10.0 v 10.0 s 56.114 

count 0 j 1 t 0.5 h 1.0 u 10.0 v 10.0 s 1425201.583 

3707208099116251.5
