In [1]:
import numpy as np
import Example_matrices as ex
import dynamic_low_rank as dlr
import time_integration_low_rank as tilr
import Variable_step_size_integrator as vssi

## Spørsmål

- Hvordan skal man kunne teste dlr?
    - hva slags A skal det fungere på
    - testing av Fu, gir matrise med elementer på størrelse $10^{-16}$  
    - (ekstra) hvordan ser man at B = CD.T
<br>

- Variable solver er litt rar.
    - kan ikke konvergere da steglengden kun minkes.

In [3]:
# testing av Fu med dlr implementasjon

A_dot = ex.A_dot(0, epsilon = 1/2)
U, S, V = vssi.construct_U_S_V_0(A_dot)

A_dot = np.array([[1,2,3],
                  [4,5,6],
                  [3,8,8]])

U, S, V = vssi.construct_U_S_V_0_k(A_dot,2)

print(U@U.T)






[[ 0.39534449  0.46453388  0.15249754]
 [ 0.46453388  0.64311625 -0.11715807]
 [ 0.15249754 -0.11715807  0.96153926]]


In [9]:
t = 1.1
h = 1
tol = 10
A = ex.A(0, epsilon = 1/2)
A_dot = ex.A_dot(0, epsilon = 1/2)
U, S, V = vssi.construct_U_S_V_0(A_dot)

In [10]:
# test av dynamic_low_rank
vals = dlr.second_order_method(h,t,U,V,S)

In [11]:
# test av variable step size integrator for dynamic low rank

# never convergeces
U1,S1,V1,j = vssi.variable_solver(0,1,A_dot,tol,h,dlr.second_order_method)

count 0 j 0 t 0 h 1 u 10.0 v 10.0 s 56.682 

action 1 sigma 58.49983172547196 tol 10
count 1 j 0 t 0 h 0.5 u 10.0 v 10.0 s 56.682 

action 1 sigma 32.45902603993742 tol 10
count 2 j 0 t 0.0 h 0.25 u 10.0 v 10.0 s 56.682 

action 1 sigma 16.255004979248746 tol 10
count 3 j 0 t 0.0 h 0.125 u 10.0 v 10.0 s 56.682 

action 2 sigma 8.187095202766255 tol 10
count 0 j 1 t 0.125 h 0.0875 u 10.0 v 10.0 s 59.538 

action 2 sigma 5.941227156449761 tol 10
count 0 j 2 t 0.2125 h 0.06124999999999999 u 10.0 v 10.0 s 61.64 

action 3 sigma 4.031242398388025 tol 0.625
count 0 j 3 t 0.27375 h 0.06124999999999999 u 10.0 v 10.0 s 63.066 

action 3 sigma 3.9448056826615847 tol 0.625
count 0 j 4 t 0.33499999999999996 h 0.06124999999999999 u 10.0 v 10.0 s 64.556 

action 3 sigma 3.7788796795093673 tol 0.625
count 0 j 5 t 0.39624999999999994 h 0.06124999999999999 u 10.0 v 10.0 s 65.984 

action 3 sigma 3.442243906970833 tol 0.625
count 0 j 6 t 0.4574999999999999 h 0.06124999999999999 u 10.0 v 10.0 s 67.281 



In [12]:
print(np.linalg.norm(U1@S1@V1-A))

92.53311630703188


In [6]:
# test av time_integration_low_rank.py
vals = tilr.second_order_method(0.5,t,U,V,S)

In [7]:
# test av variable step size integrator for time_integration_low_rank.py

U1,S1,V1,j = vssi.variable_solver(0,1,A_dot,tol,0.5,tilr.second_order_method)

A_approx = U1@S1@V1.T

print(np.linalg.norm(A_approx-A))

count 0 j 0 t 0 h 0.5 u 10.0 v 10.0 s 56.114 

count 0 j 1 t 0.5 h 1.0 u 10.0 v 10.0 s 1425201.583 

3707208099116251.5
